window.LlullsProducts = [
  {
    id: 'fleece-cielo',
    name: 'Fleece Cielo - Greyhound',
    description: 'Full-body fleece with ergonomic fit for deep chests. Soft, warm, and perfect for cooler days. Features our signature rainbow pattern in comfortable, breathable fabric.',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=900&fit=crop',
    price: '68,00',
  },
  {
    id: 'fleece-confeti-blanco',
    name: 'Fleece Confeti Blanco - Greyhound',
    description: 'Full-body fleece in white with a playful confetti pattern. Handmade, cozy, and thermal—ideal for greyhounds who feel the cold.',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=900&fit=crop',
    price: '68,00',
  },
  {
    id: 'fleece-blue',
    name: 'Fleece Blue - Greyhound',
    description: 'Classic blue fleece with red trim details. Ergonomic cut for the greyhound body—comfortable and warm for year-round layering.',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=900&fit=crop',
    price: '68,00',
  },
  {
    id: 'long-sleeve-domingo',
    name: 'Long-Sleeve Shirt Domingo - Greyhound',
    description: 'Navy and white striped long-sleeve shirt with ergonomic fit. Lightweight and perfect for mild weather or layering under a coat.',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&h=900&fit=crop',
    price: '49,00',
  },
  {
    id: 'raincoat-nimbus',
    name: 'Raincoat Nimbus - Greyhound',
    description: 'Water-resistant raincoat in blue, green, and yellow stripes. Keeps your greyhound dry and visible on rainy walks.',
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&h=900&fit=crop',
    price: '65,00',
  },
  {
    id: 'raincoat-iris',
    name: 'Raincoat Iris - Greyhound',
    description: 'Bold rainbow-striped raincoat with hood. Waterproof and designed for the greyhound silhouette—stylish and practical.',
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&h=900&fit=crop',
    price: '65,00',
  },
  {
    id: 'sleeveless-kawaii',
    name: 'Sleeveless Shirt Kawaii - Greyhound',
    description: 'Fun sleeveless shirt in a cute print. Light and breathable for warmer days—easy to put on and comfortable for all-day wear.',
    image: 'https://images.unsplash.com/photo-1589941028473-2ac882fc5762?w=800&h=900&fit=crop',
    price: '45,00',
  },
  {
    id: 'sleeveless-flower-power',
    name: 'Sleeveless Shirt Flower Power - Greyhound',
    description: 'Vibrant flower-print sleeveless shirt. Soft fabric with a flattering fit for the greyhound chest and waist.',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=900&fit=crop',
    price: '45,00',
  },
  {
    id: 'sleeveless-pink-latte',
    name: 'Sleeveless Shirt Pink Latte - Greyhound',
    description: 'Soft pink sleeveless shirt with a subtle ribbed texture. A timeless piece that pairs with any outfit or season.',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=900&fit=crop',
    price: '45,00',
  },
  {
    id: 'long-sleeve-lilax-whippet',
    name: 'Long-Sleeve Shirt Lilax - Whippet',
    description: 'Elegant long-sleeve shirt for whippets. Designed for their slender build with a comfortable, non-restrictive fit.',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=900&fit=crop',
    price: '40,00',
  },
  {
    id: 'long-sleeve-celeste-whippet',
    name: 'Long-Sleeve Shirt Celeste - Whippet',
    description: 'Sky-blue long-sleeve shirt tailored for whippets. Lightweight and perfect for spring and autumn walks.',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&h=900&fit=crop',
    price: '40,00',
  },
  {
    id: 'fleece-white-confetti-whippet',
    name: 'Fleece White Confetti - Whippet',
    description: 'White fleece with confetti pattern, made for whippets. Full-body coverage with a snug, comfortable fit.',
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&h=900&fit=crop',
    price: '58,00',
  },
];
